### ISSUE TITLE
feat: GET /v1/admin/ticket/

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#108]

**Comment by andreasfernandes93** [comment]
- [x] planning and drafting
- [x] feat: add adminGetTickets route
- [x] fix: add new fields to query in dto
- [x] feat: add AdminGetTicketsController
- [x] fix: add new fields to query in GetTicketsController
- [x] refactor: adjust logic from use case 
- [x] fix: add TicketsTotal field in TicketsWithPagination dto
- [x] refactor: Get method in ticketQueryRepo
- [x] test and review
