### ISSUE TITLE
feat: implement ProductExtraFields business rules

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#44]
Implement:
- Do not exhibit adminOnly product extra field if the requester is not an admin. That should be respected for all contexts, except during admin routes, which you can show every single field;
- Validate the value sent by the user using the regexValidation (if exists) during any type of product creation (orders routes);
- Validate if value is required during any type of product creation (orders routes);
- Validate if value sent is not one of the options available (if any option is present) during any type of product creation (orders routes);
- Replace extraFieldId on StoreProduct with a []entity.ProductExtraField cause the store should show if the extra field is required, if has options to be selected etc.

**Comment by andreasfernandes93** [comment]
Failed Attempt at Task Completion

- 02/09/24 - I started planning the task
- 03/09/24 - I put it on hold to correct PR goinfinite/bz#104.
- 04/09/24 - 11/09/24: I resumed work. 
   • Replaced the ExtrafieldId list in StoreProduct with a list of ProductExtrafieldEntities. 
   • Separated the OrgOrder repositories. 
   • Implemented the ValidateProvidedProductExtrafieldValues method in the Create and Update routes - I had a lot of difficulty implementing the method, refactoring it several times. This took a lot of time. 
   • I tried to implement a method to filter only public Extrafields in the admin routes - I had even more difficulty and didn't make progress on this implementation.
